config/routes.rb
Rails.application.routes.draw do
  resources :magazines
  resources :oenologists
  devise_for :users
  resources :strains
  resources :wines
  root "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wines_strains
    has_many :strains, through: :wines_strains, dependent: :destroy
    accepts_nested_attributes_for :wines_strains, reject_if: :all_blank, allow_destroy: true
    
    def strain_and_percent
        name_percent = []
        wines_strains.map do |ws|
            name_percent.push [ws.strain.name, ws.percent] 
        end
        name_percent.sort_by{ |strain| strain[0] }.map do |cepa|
            "#{cepa[0]} (#{cepa[1]})%"
        end.join(', ')
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  

  # GET /wines or /wines.json
  def index
    @wines = Wine.all.order('name DESC' )
    
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @strains = Strain.all
    @wine.wines_strains.build
  end

  # GET /wines/1/edit
  def edit
    @strains = Strain.all
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:score, :name, {strains_attributes: [:id, :name]}, {wines_strains_attributes:[:id, :strain_id, :percent, :_destroy]}, {strain_ids: []})
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-dark">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="links">
    <%= link_to_add_association 'add strain', form, :wines_strains %>
  </div>

<% if @wine.id.present? %>
  <div class="field text-dark">
    <%= form.label :score %>
    <%= form.number_field :score, :in =>0..100, :step => 1 %>
  </div>
  
<% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_wines_strain_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :strain_id %>
        <%= f.select :strain_id, options_from_collection_for_select(@strains, :id, :name) %>
    </div>
    <div class="field">
        <%= f.label :percent %>
        <%= f.number_field :percent %>    
    </div>
    <div class="links">
        <%= link_to_remove_association "remove task", f %>
    </div>
</div>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>


<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table class="table text-light">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Strains and Percent %</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.strain_and_percent%> </td>
        <td><%= wine.score %></td>
        <td><%= link_to 'Show', wine %></td>
         <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
          <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admin? %>
  <div>
  <%= link_to 'New Wine', new_wine_path %>
  </div>
  <div>
  <%= link_to 'New Strain', new_strain_path %>
  </div>
<% end %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>